use_frameworks!

platform :ios, '10.0'

target 'MVDPlayerSDK_Example' do
  pod 'MVDPlayerSDK', :path => '../'

  target 'MVDPlayerSDK_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
