source 'https://cdn.cocoapods.org/'
source 'https://github.com/zsk511721487/BrainMedSpec.git'

use_frameworks!

platform :ios, '13.0'

target 'MVDPlayerSDK_Example' do
#  pod 'MVDPlayerSDK', :path => '../'
  pod 'MVDPlayerSDK'
  target 'MVDPlayerSDK_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
